import "./globals.css";

import type { Metadata } from "next";

import { ThemeProvider } from "@/components/theme/theme-provider";
import ClientLayout from "@/components/layout/client-layout";
import { cn } from "@/lib/utils";
import SettingsDialogManager from "@/components/navigation/settings-dialog-manager";
import LNBWrapper from "@/components/navigation/lnb-wrapper";
import GNBWrapper from "@/components/navigation/gnb-wrapper";
import { SWRProvider } from "./swr-provider";

export const metadata: Metadata = {
  title: "hossi-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("antialiased overflow-hidden")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div>
            <LNBWrapper />
            <GNBWrapper />
            <ClientLayout>
              <SWRProvider>{children}</SWRProvider>
            </ClientLayout>
            <SettingsDialogManager />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
